---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# tempeRing

<!-- badges: start -->
<!-- badges: end -->

**PACKAGE UNDER ACTIVE DEVELOPMENT, NOT READY FOR PRODUCTION**

The goal of tempeRing is to provide an R package for my Summer Tempering project at the Warwick Statistics CDT. 

The package allows a user to run several MCMC methods, with a focus in Parallel Tempering and Annealing for multimodal targets. 

Available methods include: 

(@) Random Walk Metropolis
(@) Simulated Tempering (ST) 
(@) Parallel Tempering/Replica Exchange methods with several dynamics:

    1. Standard naive implementation
    2. Reversible dynamics via Stochastic Even-Odd swaps (SEO) *à la* Syed et. al (2021) doi: [10.1111/rssb.12464](10.1111/rssb.12464)
    3. Non-reversible dynamics via Deterministic Even-Odd swaps (DEO) *à la* **Okabe et al. (2001)** doi: [10.1016/S0009-2614(01)00055-0](10.1016/S0009-2614(01)00055-0), see also Syed et. al (2021).  
    4. Accelarated Tempering for symmetric targets via QuanTA transformations *à la* **Tawn and Roberts (2019)** doi: [10.1017/apr.2019.35](10.1017/apr.2019.35)
    5. Weight-Preservation via Hessian Adjusted Targets (HAT) *à la* **Tawn et al. (2020)** doi: [10.1007/s11222-019-09863-3](10.1007/s11222-019-09863-3)

Methods under development: 

(@) Annealed Leap-Point Sampler (ALPS) http://arxiv.org/abs/2112.12908

Future plans:

(@) Adaptive schemes
(@) Online optimal scaling

Emphasis is on allowing us to see the methods in action on illustrative toy examples and not in performance (e.g. everything is coded in R so far) but an effort was made on making the R code as efficient as possible. Faster implementations and extensions to Python and Julia are on the horizon.
